version: '3.4'
services:
  intensivao-product:
    image: cams7/intensivao-product:v001
    ports:
      - "8081:8081"
    networks:
      - intensivao-network

  intensivao-catalog:
    image: cams7/intensivao-catalog:v001
    environment:
      - PRODUCT_URL=http://intensivao-product:8081
    ports:
      - "8080:8080"
    depends_on:
      - intensivao-product
    networks:
      - intensivao-network
      
  intensivao-checkout:
    image: cams7/intensivao-checkout:v001
    environment:
      - PRODUCT_URL=http://intensivao-product:8081
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - RABBITMQ_DEFAULT_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "8082:8082"
    depends_on:
      - intensivao-product
      - rabbitmq
    networks:
      - intensivao-network

  intensivao-order-checkout:
    image: cams7/intensivao-order:v001
    command: ./order -opt checkout
    environment:
      - PRODUCT_URL=http://intensivao-product:8081
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - RABBITMQ_DEFAULT_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - REDIS_HOST=redis:6379
    depends_on:
      - intensivao-product
      - rabbitmq
      - redis
    networks:
      - intensivao-network

  intensivao-order-payment:
    image: cams7/intensivao-order:v001
    command: ./order -opt payment
    environment:
      - PRODUCT_URL=http://intensivao-product:8081
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - RABBITMQ_DEFAULT_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=/
      - REDIS_HOST=redis:6379
    depends_on:
      - intensivao-product
      - rabbitmq
      - redis
    networks:
      - intensivao-network

  intensivao-payment:
    image: cams7/intensivao-payment:v001
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_HOST=rabbitmq
      - RABBITMQ_DEFAULT_PORT=5672
      - RABBITMQ_DEFAULT_VHOST=/
    depends_on:
      - rabbitmq
    networks:
      - intensivao-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
#    volumes:
#      - /home/cams7/Desenv/Youtube/FullCycle/intensivao-microservicos/rabbitmq/data/:/var/lib/rabbitmq/
#      - /home/cams7/Desenv/Youtube/FullCycle/intensivao-microservicos/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - intensivao-network
  
  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - intensivao-network

networks:
  intensivao-network:
    driver: bridge