apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-payment-deployment
spec:
  selector:
    matchLabels:
      app: order-payment

  template:
    metadata:
      labels:
        app: order-payment
    spec:
      containers:
        - name: order-payment
          image: cams7/intensivao-order:v001
          command: ["./order"]
          args: ["-opt", "payment"]
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8081"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"            
            - name: RABBITMQ_DEFAULT_HOST
              value: "rabbitmq-service"
            - name: RABBITMQ_DEFAULT_PORT
              value: "5672"
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
            - name: REDIS_HOST
              value: "redis-service:6379"