version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:2.289.1-lts-jdk11
    privileged: true
    user: root
    ports:
      - 18080:8080
      - 15000:50000
    container_name: jenkins210604
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
